### ISSUE TITLE
[WIP] Update "Team" on GitHub

### ISSUE THREAD

**Issue by pavithraes** [nebari-dev/governance#39]
**Update the team structure and verify permissions for each team:**

_Note: The following plan is tentative to get us started, and will be updated after further discussion._

- [ ] Rename "Maintainers" to "Core"
- [ ] Rename "Emeritus maintainers" to "Emeritus core"
- [ ] Create a new "Owners" team (name TBD) -- folks who have [owner role](https://github.com/orgs/nebari-dev/people?query=role%3Aowner) and can add/remove team members. Alternatively, we can give "Core" team these rights?
- [ ] Verify permissions for each team:
  - [ ] "Triage" team should be able to add/remove issue and pr labels across all repos in the org, ensure they can transfer issues across repos
  - [ ] "Design" team should have merge rights only on `nebari-dev/design`
  - [ ] "Documentation" team should have merge rights only on `nebari-dev/nebari-doc`
  - [ ]  "Contributors" team should have merge rights across all repos in the org
  - [ ] "Core" team can update things at the org level in addition to "Contributor" privileges (?) Alternatively, this team can be for recognizing decision makers.
  - [ ] "Emeritus core" members should have no special access, this team is for recognizing past contributions.

**References:**

- Nebari teams: https://github.com/orgs/nebari-dev/teams
- https://docs.github.com/en/get-started/learning-about-github/access-permissions-on-github
- https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/repository-roles-for-an-organization#permissions-for-each-role

cc @trallard

**Comment by trallard** [comment]
There is an owner team - but it is private

**Comment by pavithraes** [comment]
Done!
