### ISSUE TITLE
RFD - Remove support for Digital Ocean

### ISSUE THREAD

**Issue by Adam-D-Lewis** [nebari-dev/governance#50]
| Status            | Accepted ✅|
| ----------------- | --------------------------------------------------------------------------------------- |
| Author(s)         | @Adam-D-Lewis                                                                            |
| Date Created      | 02-07-2024                                                                               |
| Date Last updated | 02-07-2024                                                                               |
| Decision deadline | 01-08-2024                                                                               |

# Remove support for Digital Ocean

## Summary
We aren't aware of any Nebari deployments on Digital Ocean deployments.  In order to focus development resources on parts of Nebari that are in use and thus will result in more benefit to users, we are planning to deprecate support for Digital Ocean.  

Digital Ocean would still be supported via the "existing" provider ([docs here](https://www.nebari.dev/docs/how-tos/nebari-kubernetes/)).  The difference would be you need to set up the node groups on your own beforehand.

Please comment if you are using Digital Ocean deployment, and would get value from us continuing to support Digital Ocean as an officially supported provider.

## User benefit

More focus on used features

### Best practices

We will likely add a deprecation message during the update or deploy step to advise users.  Then we will remove Digital Ocean support in a following release.

**Comment by Adam-D-Lewis** [comment]
Digital Ocean deprecation message has been added to the 2024.7.1 release

**Comment by Adam-D-Lewis** [comment]
Digital Ocean support is being removed shortly - https://github.com/nebari-dev/nebari/issues/2749.
 Will close when done.

**Comment by marcelovilla** [comment]
I'm closing this RFD because DigitalOcean support was removed in https://github.com/nebari-dev/nebari/pull/2838
